---
- name: "Terminate {{ ec2_instance_name }} EC2 Instance In AWS"
  hosts: localhost
  gather_facts: true
  become: false
  vars: 
    region: us-east-1
   
  roles:
  
    - Get_List_Of_EC2_Instances_In_Specific_AZ
    #- Deleting_A_EC2_Instance

