---
- name: Update Current System Facts
  ansible.builtin.setup:

- name: Set specific_ec2_instance_detected_var Again
  set_fact:
    specific_ec2_instance_detected_var: "{{ hostvars['localhost']['specific_ec2_instance_detected_var'] }}"
  when: "hostvars['localhost']['specific_ec2_instance_detected_var'] is defined"


- name: Include terminate_EC2_Instance_On_AWS.yml File
  ansible.builtin.include_tasks:
    file: terminate_EC2_Instance_On_AWS.yml
  when: "specific_ec2_instance_detected_var is defined"



- name: "{{ ec2_instance_name }} Instance Not Detected In specific_ec2_instance_detected_var"
  ansible.builtin.debug:
    msg: "{{ specific_ec2_instance_detected_var  | default(omit) }}"
  when: "specific_ec2_instance_detected_var is not defined"
