    
    
- name: "Get List Of EC2 Instances In {{ aws_az }}"
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ aws_az }}"
  register: ec2_instance_list_output



- name: Set specific_ec2_instance_detected_var To True
  set_fact:
    specific_ec2_instance_detected_var: "true"
  loop: "{{ ec2_instance_list_output }}"
  when: "ec2_instance_name in item.tags[0]"




- name: Print ec2_instance_list_output
  ansible.builtin.debug:
    msg: "{{ ec2_instance_list_output }}"


    


 