    
    
- name: "Get List Of EC2 Instances In {{ aws_az }}"
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ aws_az }}"
  register: ec2_instance_list_output



- name: Set specific_ec2_instance_detected_var Variable
  set_fact:
    specific_ec2_instance_detected_var: "{{ item.tags.Name }}"
  loop: "{{ ec2_instance_list_output.instances }}"
  when: "ec2_instance_name in item.tags.Name"




# - name: Print ec2_instance_list_output
#   ansible.builtin.debug:
#     msg: "{{ ec2_instance_list_output }}"


# - name: Print ec2_instance_list_output debug
#   ansible.builtin.debug:
#     msg: "{{ ec2_instance_list_output.instances[0].tags }}"


- name: Print specific_ec2_instance_detected_var
  ansible.builtin.debug:
    msg: "{{ specific_ec2_instance_detected_var }}"
